
INSERT INTO public.fake_reviews (reviewer_name, reviewer_location, rating, content, sort_order, is_visible)
SELECT name, loc, rating, content, ord, true FROM (VALUES
('Ahmed Khan','Lahore, Pakistan',5,'Best earning platform I have used. Withdrawals are fast and support is friendly.',1),
('Ayesha Siddiqui','Karachi, Pakistan',5,'I made my first 5000 PKR in just one week. Highly recommended for students.',2),
('Bilal Ahmad','Islamabad, Pakistan',4,'Tasks are easy and instructions are clear. Payment received on time.',3),
('Fatima Noor','Multan, Pakistan',5,'Truly life changing. The video tasks are simple and rewarding.',4),
('Hassan Raza','Faisalabad, Pakistan',5,'Customer support replied within minutes. Trustworthy platform.',5),
('Sana Malik','Rawalpindi, Pakistan',5,'Withdrew via JazzCash, received in 10 minutes. Amazing!',6),
('Usman Tariq','Peshawar, Pakistan',4,'Good packages and consistent earnings. Will recommend to friends.',7),
('Hira Iqbal','Quetta, Pakistan',5,'Best decision to join. Easy work, real money.',8),
('Zain Abbas','Sialkot, Pakistan',5,'I am a college student and this helps cover my expenses.',9),
('Maryam Sheikh','Gujranwala, Pakistan',5,'Smooth experience from signup to first withdrawal.',10),
('Imran Hussain','Hyderabad, Pakistan',5,'Genuine site with real payments. Loved it.',11),
('Nida Ali','Sargodha, Pakistan',4,'Tasks are simple and the dashboard is clean.',12),
('Junaid Akhtar','Bahawalpur, Pakistan',5,'My family appreciates the extra income I bring.',13),
('Rabia Yousaf','Sukkur, Pakistan',5,'No hidden charges, withdrawals are quick.',14),
('Adeel Mehmood','Mirpur, Pakistan',5,'Investment paid back in under two weeks. Worth it.',15),
('Sadia Rehman','Sahiwal, Pakistan',4,'Reliable and easy to understand for beginners.',16),
('Kashif Naveed','Okara, Pakistan',5,'I was skeptical at first but now I trust them fully.',17),
('Mahnoor Javed','Sheikhupura, Pakistan',5,'Beautiful UI and very smooth experience.',18),
('Faisal Shahzad','Mardan, Pakistan',4,'Earnings credited instantly after task review.',19),
('Anum Aslam','Abbottabad, Pakistan',5,'My pocket money source for the last 3 months.',20),
('Salman Khalid','Larkana, Pakistan',5,'Pays daily without delays. Best platform in Pakistan.',21),
('Iqra Naeem','Wah Cantt, Pakistan',5,'Withdrawals via Easypaisa work perfectly.',22),
('Owais Ahmed','Sukkur, Pakistan',5,'Helpful tutorials and clear payment proofs.',23),
('Tahir Mehmood','Kasur, Pakistan',4,'A trustworthy platform for online earning.',24),
('Komal Tariq','Mingora, Pakistan',5,'I love the new wallet UI. Looks premium.',25),
('Asad Iqbal','Chiniot, Pakistan',5,'Earned 25k in my first month after upgrading package.',26),
('Sumaira Aslam','Jhelum, Pakistan',5,'Their support team is amazing.',27),
('Rashid Mahmood','Sahiwal, Pakistan',5,'Fast, reliable and transparent.',28),
('Saba Ehsan','Multan, Pakistan',4,'I refer all my friends now. Genuine site.',29),
('Hamza Riaz','Lahore, Pakistan',5,'Earnings reach my wallet within minutes.',30),
('Nadia Imran','Karachi, Pakistan',5,'I do tasks during free time and earn well.',31),
('Talha Munir','Islamabad, Pakistan',5,'Honest platform with timely payouts.',32),
('Areeba Tariq','Rawalpindi, Pakistan',5,'A blessing for housewives like me.',33),
('Shahid Anwar','Faisalabad, Pakistan',4,'Simple to use even for non-tech people.',34),
('Mariam Saeed','Quetta, Pakistan',5,'I doubled my package within 20 days.',35),
('Yasir Pervez','Peshawar, Pakistan',5,'Best earning app I have ever joined.',36),
('Hina Shahbaz','Sialkot, Pakistan',5,'Smooth, secure and rewarding.',37),
('Numan Ashraf','Sargodha, Pakistan',4,'Watching videos and getting paid, what else?',38),
('Tehmina Rauf','Bahawalpur, Pakistan',5,'Withdrawals confirmed in less than an hour.',39),
('Waleed Khan','Hyderabad, Pakistan',5,'Solid platform for daily income.',40),
('Sehrish Aslam','Mirpur, Pakistan',5,'Earnings always credited accurately.',41),
('Zubair Ali','Sukkur, Pakistan',4,'I trust them with my investment.',42),
('Aqsa Rafiq','Sahiwal, Pakistan',5,'Best customer support team ever.',43),
('Hammad Bashir','Okara, Pakistan',5,'Genuine earnings, fast payments.',44),
('Rida Fatima','Sheikhupura, Pakistan',5,'My monthly bills are now easier to pay.',45),
('Babar Iqbal','Mardan, Pakistan',5,'Wallet UI is beautiful, withdrawals reliable.',46),
('Sidra Aslam','Abbottabad, Pakistan',4,'Started part time, now full time earner.',47),
('Naveed Iqbal','Larkana, Pakistan',5,'No scam, real money. Trust me.',48),
('Faiza Naeem','Wah Cantt, Pakistan',5,'I keep recommending to family.',49),
('Wajid Ali','Mingora, Pakistan',5,'Earnings are higher than expected.',50),
('Mehwish Akram','Chiniot, Pakistan',5,'Payments received within minutes.',51),
('Khurram Shahzad','Jhelum, Pakistan',5,'Great platform, fully reliable.',52),
('Iram Khan','Kasur, Pakistan',4,'Lovely interface and easy tasks.',53),
('Daniyal Tariq','Lahore, Pakistan',5,'Wonderful earning opportunity.',54),
('Nimra Shafiq','Karachi, Pakistan',5,'I love their package plans.',55),
('Mubashir Ahmad','Islamabad, Pakistan',5,'Best online earning platform in 2026.',56),
('Sana Tariq','Rawalpindi, Pakistan',5,'Helpful for students and housewives.',57),
('Awais Mehmood','Faisalabad, Pakistan',4,'Earnings credited as promised.',58),
('Tooba Khalid','Multan, Pakistan',5,'Reliable and very rewarding.',59),
('Hafiz Bilal','Peshawar, Pakistan',5,'Trustworthy, with quick withdrawals.',60),
('Saima Younas','Quetta, Pakistan',5,'I love their team and product.',61),
('Faraz Ahmed','Sialkot, Pakistan',5,'No issues at all so far.',62),
('Aliya Imran','Sargodha, Pakistan',4,'My favorite earning app of the year.',63),
('Sufyan Khan','Bahawalpur, Pakistan',5,'Easy money, simple tasks.',64),
('Yusra Hassan','Hyderabad, Pakistan',5,'Recommended to my whole family.',65),
('Asim Raza','Sukkur, Pakistan',5,'Best platform for beginners.',66),
('Bushra Naseem','Mirpur, Pakistan',5,'Smooth experience, fast payouts.',67),
('Hashim Ali','Sahiwal, Pakistan',4,'A wonderful side hustle.',68),
('Hafsa Imran','Okara, Pakistan',5,'I love working with them.',69),
('Mohsin Tahir','Sheikhupura, Pakistan',5,'My monthly earnings keep growing.',70),
('Sobia Yousaf','Mardan, Pakistan',5,'Honest and reliable platform.',71),
('Arsalan Aziz','Abbottabad, Pakistan',5,'Worth every rupee invested.',72),
('Ramsha Khan','Larkana, Pakistan',4,'Best decision of 2026.',73),
('Touseef Ahmad','Wah Cantt, Pakistan',5,'Real platform with real payments.',74),
('Zahra Asif','Mingora, Pakistan',5,'Earnings credited daily.',75),
('Saqib Mehmood','Chiniot, Pakistan',5,'Top notch support team.',76),
('Mahrukh Iqbal','Jhelum, Pakistan',5,'I love the new mobile design.',77),
('Asfand Yar','Kasur, Pakistan',4,'Pays well and on time.',78),
('Laiba Hashmi','Lahore, Pakistan',5,'Quality earning platform.',79),
('Adnan Saeed','Karachi, Pakistan',5,'No delays in withdrawals.',80),
('Hadia Rauf','Islamabad, Pakistan',5,'Excellent earning opportunity.',81),
('Mudassar Riaz','Rawalpindi, Pakistan',5,'Real, reliable and rewarding.',82),
('Tayyaba Anwar','Faisalabad, Pakistan',4,'Honest and clear instructions.',83),
('Raheel Khan','Multan, Pakistan',5,'Lots of earning options.',84),
('Sumaiya Tariq','Peshawar, Pakistan',5,'Lovely mobile experience.',85),
('Shoaib Asghar','Quetta, Pakistan',5,'Trustworthy team and product.',86),
('Iqra Shahid','Sialkot, Pakistan',5,'Smooth from start to finish.',87),
('Farhan Aslam','Sargodha, Pakistan',4,'I use it daily, no issues.',88),
('Mehak Bilal','Bahawalpur, Pakistan',5,'Best earning app this year.',89),
('Ammar Saeed','Hyderabad, Pakistan',5,'I love their dashboard.',90),
('Sajida Bibi','Sukkur, Pakistan',5,'Great support for new users.',91),
('Naeem Shah','Mirpur, Pakistan',5,'Premium experience all the way.',92),
('Lubna Sajid','Sahiwal, Pakistan',4,'Easy to learn and earn.',93),
('Saad Hussain','Okara, Pakistan',5,'Quick withdrawals, no delays.',94),
('Zoya Khalid','Sheikhupura, Pakistan',5,'Wonderful side income source.',95),
('Tariq Mahmood','Mardan, Pakistan',5,'A premium and trusted platform.',96),
('Nashit Ali','Abbottabad, Pakistan',5,'Best in class earning app.',97),
('Mariyam Iqbal','Larkana, Pakistan',4,'My family loves it too.',98),
('Hussain Raza','Wah Cantt, Pakistan',5,'I depend on it now for income.',99),
('Sehar Ahmed','Mingora, Pakistan',5,'Truly amazing experience.',100),
('Faizan Asif','Chiniot, Pakistan',5,'Fully recommend to everyone.',101),
('Areej Imran','Jhelum, Pakistan',5,'I am so happy I joined.',102),
('Maaz Khalil','Kasur, Pakistan',5,'Great earning per task.',103),
('Sundas Ali','Lahore, Pakistan',5,'Best mobile earning experience.',104),
('Asadullah Khan','Karachi, Pakistan',5,'Five stars all the way.',105)
) AS t(name, loc, rating, content, ord)
WHERE NOT EXISTS (SELECT 1 FROM public.fake_reviews WHERE reviewer_name = t.name AND content = t.content);
